"""INP/FEM workflow coordination layer.

This module keeps the historical `inp_service` import path stable while using
plain, explicit imports to expose the split catalog / matching / result /
correlation services.
"""

from . import fem_catalog_service as _catalog
from . import fem_matching_service as _matching
from . import fem_response_service as _response
from . import fem_result_service as _result
from . import fem_correlation_service as _correlation

# Shared dependencies kept here for backward compatibility with existing code
# and tests that import or monkeypatch them from inp_service directly.
os = _catalog.os
np = _catalog.np
json = _catalog.json
parse_inp = _catalog.parse_inp
get_connection = _catalog.get_connection
ensure_tables_exist = _catalog.ensure_tables_exist
settings = _catalog.settings
ValidationError = _catalog.ValidationError
NotFoundError = _catalog.NotFoundError
RegistryRepo = _catalog.RegistryRepo
safe_write_console_event = _catalog.safe_write_console_event
log_project_error = _catalog.log_project_error
log_project_info = _catalog.log_project_info
log_project_step = _catalog.log_project_step
get_test_data_mode = _catalog.get_test_data_mode
get_node_match_parameter_context = _catalog.get_node_match_parameter_context
save_fem_model_dimensions = _catalog.save_fem_model_dimensions
resolve_project_cal_subdir = _catalog.resolve_project_cal_subdir
resolve_project_source_inp_path = _catalog.resolve_project_source_inp_path
update_work_condition_project_status = _catalog.update_work_condition_project_status

# Historical private helpers/constants that other modules still import from
# inp_service. Keep them as explicit aliases instead of relying on `import *`.
_sens = _catalog._sens
_parse_id_list = _catalog._parse_id_list
_parse_optional_json_object = _catalog._parse_optional_json_object
_SUPPORTED_CORRECTION_QUANTITIES = _catalog._SUPPORTED_CORRECTION_QUANTITIES
_clear_import_inp_catalog_tables = _catalog._clear_import_inp_catalog_tables
_extract_legacy_material_rows = _catalog._extract_legacy_material_rows
_extract_legacy_property_rows = _catalog._extract_legacy_property_rows
_extract_legacy_boundary_rows = _catalog._extract_legacy_boundary_rows
_quantity_description = _catalog._quantity_description
_build_inp_parameter_options = _catalog._build_inp_parameter_options
_extract_quantity_set_capabilities = _catalog._extract_quantity_set_capabilities
_save_octree_cache = _catalog._save_octree_cache
_load_octree_cache = _catalog._load_octree_cache
_cache_part_lookup = _catalog._cache_part_lookup
_require_modal_project = _catalog._require_modal_project
_require_non_modal_project = _catalog._require_non_modal_project
_required_operation_error = _catalog._required_operation_error
_DEFAULT_RESPONSE_SCATTER = _catalog._DEFAULT_RESPONSE_SCATTER
_get_latest_octree_meta = _matching._get_latest_octree_meta
_ensure_octree_cache_file = _matching._ensure_octree_cache_file
_ensure_node_matches = _correlation._ensure_node_matches
_ensure_static_node_matches = _correlation._ensure_static_node_matches
_resolve_modal_mac_mode = _correlation._resolve_modal_mac_mode
_load_test_modal_frequencies = _correlation._load_test_modal_frequencies
_compute_dac_dsf = _correlation._compute_dac_dsf
_load_modal_payload = _result._load_modal_payload
_resolve_modal_node_identity = _result._resolve_modal_node_identity
_manifest_result_group_clause = _result._manifest_result_group_clause
_registry_repo = _result._registry_repo
_resolve_project_result_workspace = _result._resolve_project_result_workspace
_collect_project_result_static_rows = _result._collect_project_result_static_rows
_load_static_result_rows_from_txt = _result._load_static_result_rows_from_txt
_load_static_result_payload = _result._load_static_result_payload
_persist_fe_static_results = _result._persist_fe_static_results
_build_static_alignment = _correlation._build_static_alignment
_build_static_analysis_error_rows = _correlation._build_static_analysis_error_rows
_load_modal_correlation_rows = _correlation._load_modal_correlation_rows
_ensure_modal_correlation_rows = _correlation._ensure_modal_correlation_rows

# Catalog / parameter workflows.
import_inp_catalog = _catalog.import_inp_catalog
get_inp_catalog = _catalog.get_inp_catalog
get_inp_parameter_options = _catalog.get_inp_parameter_options
get_project_abaqus_instances_and_steps = _catalog.get_project_abaqus_instances_and_steps
resolve_abaqus_instance_context = _catalog.resolve_abaqus_instance_context
validate_abaqus_instance_node_label = _catalog.validate_abaqus_instance_node_label
create_optimization_parameter = _catalog.create_optimization_parameter
create_design_response_catalog_entry = _catalog.create_design_response_catalog_entry
list_design_response_catalog_entries = _catalog.list_design_response_catalog_entries
clear_design_response_catalog_entries = _catalog.clear_design_response_catalog_entries

# Matching workflows.
match_test_nodes = _matching.match_test_nodes
get_pair_node_point_result = _matching.get_pair_node_point_result
save_transform_operation = _matching.save_transform_operation
get_transform_auto_info = _matching.get_transform_auto_info
match_test_dofs = _matching.match_test_dofs
get_dof_matches = _matching.get_dof_matches

# Response catalog workflows.
build_fe_response_catalog = _response.build_fe_response_catalog
get_fe_response_catalog = _response.get_fe_response_catalog
list_optimization_parameters = _response.list_optimization_parameters
update_optimization_parameter_usage = _response.update_optimization_parameter_usage
select_optimization_parameters_for_update = _response.select_optimization_parameters_for_update
remove_optimization_parameters_from_update = _response.remove_optimization_parameters_from_update
get_modal_frequency_response_options = _response.get_modal_frequency_response_options
create_modal_frequency_response_catalog_from_fem = _response.create_modal_frequency_response_catalog_from_fem
create_modal_frequency_response_catalog_from_match = _response.create_modal_frequency_response_catalog_from_match
create_modal_match_response_catalog_entries = _response.create_modal_match_response_catalog_entries

# Result import workflows.
import_fe_modal_results = _result.import_fe_modal_results
get_fe_modal_results = _result.get_fe_modal_results
import_fe_static_results = _result.import_fe_static_results
import_fe_static_results_from_project_result = _result.import_fe_static_results_from_project_result
get_fe_static_results = _result.get_fe_static_results

# Correlation / evaluation workflows.
store_updated_static_analysis_error = _correlation.store_updated_static_analysis_error
compute_static_correlation = _correlation.compute_static_correlation
evaluate_static_correlation = _correlation.evaluate_static_correlation
compute_modal_correlation = _correlation.compute_modal_correlation
get_modal_correlation = _correlation.get_modal_correlation
get_modal_correlation_matrix_payload = _correlation.get_modal_correlation_matrix_payload
get_modal_correlation_table_payload = _correlation.get_modal_correlation_table_payload
get_modal_scale_factor = _correlation.get_modal_scale_factor
get_modal_scale_factor_table_payload = _correlation.get_modal_scale_factor_table_payload
get_modal_match_frequency_scatter_payload = _correlation.get_modal_match_frequency_scatter_payload
get_modal_frequency_consistency_payload = _correlation.get_modal_frequency_consistency_payload
get_modal_correlation_all_scatter_payload = _correlation.get_modal_correlation_all_scatter_payload
preview_modal_match = _correlation.preview_modal_match
match_modal_modes = _correlation.match_modal_modes
